POST http://localhost:3000/postEvents
Content-Type: application/json

{
    "username":"bharath",
    "email":"mandabharath49@gmail.com",
    "phone":"8247360108",
    "eventType":"Birthday Party"
}

###

Get http://localhost:3000/getEvents
